- .gitignore
- AUTHORS.txt
- src/psd_tools/__init__.py
- src/psd_tools/decoder/linked_layer.py
- src/psd_tools/decoder/tagged_blocks.py
- src/psd_tools/user_api/__init__.py
- src/psd_tools/user_api/embedded.py
- src/psd_tools/user_api/psd_image.py
- tests/test_placed_layer.py
Access for embedded files, these are called embedded smart objects by Adobe I think.
I'm using this to save embbedded Illustrator files as SVG without using any Adobe product using
for i, emb in enumerate(psd.embedded):
emb.save_as_svg('/tmp/psdexport/icon-{0}.svg'.format(i))
> extraction of embedded files

- src/psd_tools/user_api/pil_support.py
Version 1.1.7 of PIL seems to lack tobytes. I think someone messed up on the 2 to 3 conversion. Unfortunately I can't upgrade right away...
I didn't want to patch PIL globally so just doing it on the object
> monkey patch for PIL 1.1.7 for CMYK files

- src/psd_tools/decoder/actions.py
The interaction I ran into involved smart objects and smart filters, but I couldn't manage to reproduce the problem in a fresh PSD. I've uploaded a rather large failing PSD here as an example.
Failing PSD: [test_enum.psd.zip](https://github.com/psd-tools/psd-tools/files/52968/test_enum.psd.zip)
> Fix incorrect conditional when attempting to decode references.

- src/psd_tools/debug.py
The `verbose` argument for Python's `collections.namedtuple()` changed to keyword-only in >= Python3.6 (see https://docs.python.org/3/library/collections.html#collections.namedtuple)
This PR changes `debug.py` to reflect that.
> namedtuple's verbose argument changed to keyword-only in Python 3.6

- src/psd_tools/composite/__init__.py
This PR is to fix #299.
There is sometimes a layer in PSD with `stroke` but without `vector_mask`, which result in an error when attributes of `layer.vector_mask` are accessed in `layer.composite()`. We just skip rendering strokes when the layer has no vector mask.
> Check if a layer has vector mask before rendering strokes

- .github/workflows/ci.yml
- .readthedocs.yaml
- Update `cibuildwheel` to v2.5.0
- Skip slow `aarch64` tests on QEMU
- Update `gh-action-pypi-publish` to `release/v1`
> Update actions packages

- src/psd_tools/api/layers.py
- src/psd_tools/api/pil_io.py
- src/psd_tools/api/psd_image.py
- src/psd_tools/composite/__init__.py
- tests/psd_tools/composite/test_composite.py
Proposing a number of improvements to better support other image modes (mainly using CMYK) in `layer.topil` and `layer.composite`.  As listed below:
- Apply icc profile to non-rgb images (by converting them to RGB image mode). As stated in the [pillow documentation](https://pillow.readthedocs.io/en/stable/_modules/PIL/ImageCms.html#profileToProfile), the output image mode is by default the same as the input image mode. When applying the ICC profile on a CMYK image to convert it to sRGB profile, we need to explicitly set the output image mode to something that is RGB.
- Enable transparency for images not in RGB or L image mode (i.e. CMYK) in layer.topil() when the icc_profile is enabled. This is done by changing the order of operation: apply the ICC profile first without transparency, then …
> Improvements for non-rgb modes and transparency

- src/psd_tools/psd/layer_and_mask.py
Workaround for the assertion error (fix #316)
Changes:
- Emit warning instead of assertion error for a broken PSD file
> Emit warning only when LayerAndMaskInformation is broken

- src/psd_tools/api/shape.py
I have see a user-uploaded file that psd-tools can't read. This file was produced by Affinity Photo 1.10.4 and exported as PSD.
The file was failing in the `Stroke` constructor at `assert self._data.classID == b"strokeStyle"`. Instead the `classId` is `Strk`
Photoshop doesn't have a problem opening this file, and does so without warning. So the classId check can be either relaxed (accept 2 values) or removed entirely.
Just wondering if it is best to allow 2 values here, or to remove the assert altogether?
> Accept other classId in Stroke constructor

- src/psd_tools/composite/blend.py
- tests/psd_tools/composite/test_blend.py
Fixes #233 
I found a minor order of operations bug in _set_sat and fixed that.
I also changed vivid light to use color burn and color dodge directly. This produces the exact same result as `[TS] Vivid Light` in Paint Tool SAI and `Vivid Light` in Clip Studio Paint, which is supposed to be the same as Photoshop, however I don't have Photoshop to verify. This change seems to contradict the original comment about using Photoshop's Hard Mix, but I think this produces the 'correct' result, or at least the result seems more correct (visually and aesthetically).
> Fix hue, sat, and vivid light

- src/psd_tools/composite/__init__.py
- src/psd_tools/composite/effects.py
In my last PR [here](https://github.com/psd-tools/psd-tools/pull/361).
I missed a couple of call sites when adding an argument to `draw_solid_color_fill`.
This causes the following error:
```
TypeError: draw_solid_color_fill() missing 1 required positional argument: 'desc'
```
Sorry if anyone was affected by this bug in the 1.9.29 release (4 days old)
cc: @kyamagu
> fix missing arguments when calling draw_solid_color_fill

- src/psd_tools/constants.py
Photoshop introduced new colors, a total of 11.
Saved the file, tried to open with new sheet color, found the missing number, added it to the list. did it for all of them.
> Added new Sheet Colors

- src/psd_tools/api/numpy_io.py
This fixes the case when a PSD has alpha channels that aren't transparency and this isn't indicated in one of the other ways `has_transparency` checks. The spec says if layer count is negative it indicates the merged preview image has a transparent alpha channel, otherwise it does not.
From https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_16000:
> Layer count. If it is a negative number, its absolute value is the number of layers and the first alpha channel contains the transparency data for the merged result.
Closes #369
> Fix merged preview image having transparency when it shouldn't

- MANIFEST.in
- pyproject.toml
v1.9.29 is broken as the pyx file is not included in the build
> fix: include pyx file in build

- .gitignore
- src/psd_tools/compression/_rle.pyx
- src/psd_tools/compression/rle.py
Hi! Thanks for developing this awesome tool. 
I've been looking for ways to compress PSDs while still having them natively readable by Photoshop, and I came up with a slightly more space efficient PackBits encoding algorithm. It admittedly only saves a tiny amount of space compared to Photoshop's implementation, but I thought it was still worth making a PR here.
I also took the time to refactor the rest of the RLE module here, since it was possible to simplify and optimise the code a bit. Most of the performance gains are from removing the overhead of calling extra Python functions.
You'll also notice that I swapped out raw C strings for C++ strings in the Cython code, this just makes it far easier to sit back and let Cython and C++ manage the memory and type conversions. If you'd prefer …
> reworked packbits/rle algorithms

- src/psd_tools/api/psd_image.py
Some PSDs contain dividers with SectionDivider.OTHER. Ignoring the dividers, allows the correct categorization of the layer.
> Fix #338: correct layer kind for PSDs containing dividers with SectionDivider.OTHER

- src/psd_tools/api/smart_object.py
I suggest this PR to expose and document a new property for SmartObject: `transform_box`
It comes from the `transform` property of the PlacedLayerData TaggedBlock. It is a tuple with 8 items (x1, y1, x2, y2, x3, y3, x4, y4) where 1 is top left corner, 2 is top right, 3 is bottom right and 4 is bottom left.
I chose to rename it in order to avoid confusion with the `transform` property of TypeLayer which is a tuple with 6 items (xx, xy, yx, yy, tx, ty) and is an affine transformation matrix.
> Add a new property to SmartObject: transform_box

- docs/reference/psd_tools.constants.rst
- src/psd_tools/api/layers.py
- src/psd_tools/constants.py
Type layers can contain texts of 2 types : point (character) or paragraph (area).
The information is stored in EngineDict and this PR introduces a new property `text_type` for TypeLayer. 
It also introduces a new TextType constant.
> Add new property text_type for TypeLayer

- src/psd_tools/compression/__init__.py
I encountered a PSD with a layer that causes psd-tools to halt with ValueError ("Invalid RLE compression") when calling composite() on a specific channel in a specific layer. I wasn't able to debug the decoding function (_rle.pyx). 
It is possible that the RLE data is corrupted or invalid.
In any case, I think psd-tools should not fail in this situation. Now when a channel cannot be decoded, it is replaced with an empty channel (black). The colors of the composited image are of course off because one channel is missing, but at least it doesn't entirely fail. 
I also added logging to inform the user of the RLE decoding error and the fallback channel that was created.
> Don't stop on RLE decoding errors but generate an empty channel (black)

- src/psd_tools/api/effects.py
- src/psd_tools/api/layers.py
Hi, 
I made the fix for the conversion issue mentioned in https://github.com/psd-tools/psd-tools/issues/433, i went with the composite() function.
I refactored the functions for layer validity verification and metadata update.
In the latter i added something to retrieve the effect patterns from a psd to add to the new one when moving a layer around. As i encountered an issue for psd opening concerning this. There may be other things to consider in this case, I guess those will be found along the way.
I also added functions for searching layers by name. Yielding either the first match, or a generator of all of them.
> Conversion issue fix, Layer metadata refactor, effect pattern transfer

- src/psd_tools/api/layers.py
- tests/psd_tools/api/test_layers.py
Fix for issue https://github.com/psd-tools/psd-tools/issues/437.
The artboard _move function will set the _bounding_records, _bounding_channels.
> Artboard lacking the bounding record/channels fix.

- pyproject.toml
- src/psd_tools/api/__init__.py
- src/psd_tools/api/adjustments.py
- src/psd_tools/api/effects.py
- src/psd_tools/api/layers.py
- src/psd_tools/api/mask.py
- src/psd_tools/api/numpy_io.py
- src/psd_tools/api/pil_io.py
- src/psd_tools/api/psd_image.py
- src/psd_tools/api/shape.py
- src/psd_tools/api/smart_object.py
- src/psd_tools/composite/__init__.py
- src/psd_tools/composite/blend.py
- src/psd_tools/composite/effects.py
- src/psd_tools/composite/vector.py
- src/psd_tools/compression/__init__.py
- src/psd_tools/compression/rle.py
- src/psd_tools/psd/image_resources.py
- src/psd_tools/psd/layer_and_mask.py
- src/psd_tools/psd/patterns.py
- src/psd_tools/psd/tagged_blocks.py
- tests/psd_tools/api/test_layers.py
Changes:
- Add type annotation to high-level APIs.
- Change `apply_icc = True` by default (Resolve #445)
> Add type annotation to high-level packages

- docs/usage.rst
- src/psd_tools/api/psd_image.py
Updates the ImageData section when saving the psd if the layer structure was updated.
> Force image data update on saving

- src/psd_tools/psd/linked_layer.py
Files produced by photoshop 26.9.0 (from July 2025) use layer version 8.
See issue raised [here](https://github.com/psd-tools/psd-tools/issues/474)
> allow linked layer version 8

- setup.py
Changes:
- Fix incorrect Py_LIMITED_API version in hex.
This resolves the following warning:
```
RuntimeWarning: compile time Python version 3.19 of module 'psd_tools.compression._rle' was newer than runtime version 3.14
```
> Fix incorrect Py_LIMITED_API version

- tests/psd_tools/api/test_adjustments.py
- tests/psd_tools/api/test_effects.py
- tests/psd_tools/api/test_layers.py
- tests/psd_tools/api/test_mask.py
- tests/psd_tools/api/test_numpy_io.py
- tests/psd_tools/api/test_pil_io.py
- tests/psd_tools/api/test_psd_image.py
- tests/psd_tools/api/test_shape.py
- tests/psd_tools/api/test_smart_object.py
- tests/psd_tools/composite/test_composite.py
- tests/psd_tools/compression/test_compression.py
- tests/psd_tools/psd/test_adjustments.py
- tests/psd_tools/psd/test_base.py
- tests/psd_tools/psd/test_color_mode_data.py
- tests/psd_tools/psd/test_descriptor.py
- tests/psd_tools/psd/test_effects_layer.py
- tests/psd_tools/psd/test_engine_data.py
- tests/psd_tools/psd/test_filter_effects.py
- tests/psd_tools/psd/test_header.py
- tests/psd_tools/psd/test_image_data.py
- tests/psd_tools/psd/test_image_resources.py
- tests/psd_tools/psd/test_layer_and_mask.py
- tests/psd_tools/psd/test_linked_layer.py
- tests/psd_tools/psd/test_patterns.py
- tests/psd_tools/psd/test_psd.py
- tests/psd_tools/psd/test_vector.py
- tests/psd_tools/test_main.py
- tests/psd_tools/test_utils.py
- tests/psd_tools/utils.py
Changes:
- Drop python 2.x compatibility in the tests
- Drop IPython-dependent tests in favor of standard pprint
> Drop python2 compatibility
